In [2]:
!pip install kagglehub

Requirement already satisfied: kagglehub in c:\users\bethw\anaconda3\lib\site-packages (1.0.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.14 in c:\users\bethw\anaconda3\lib\site-packages (from kagglehub) (0.1.20)
Requirement already satisfied: packaging in c:\users\bethw\anaconda3\lib\site-packages (from kagglehub) (23.1)
Requirement already satisfied: pyyaml in c:\users\bethw\anaconda3\lib\site-packages (from kagglehub) (6.0)
Requirement already satisfied: requests in c:\users\bethw\anaconda3\lib\site-packages (from kagglehub) (2.31.0)
Requirement already satisfied: tqdm in c:\users\bethw\anaconda3\lib\site-packages (from kagglehub) (4.65.0)
Requirement already satisfied: protobuf in c:\users\bethw\anaconda3\lib\site-packages (from kagglesdk<1.0,>=0.1.14->kagglehub) (4.25.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\bethw\anaconda3\lib\site-packages (from requests->kagglehub) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\bethw\anaconda3\lib\site-packages (from requests->kagglehub) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\bethw\anaconda3\lib\site-packages (from requests->kagglehub) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\bethw\anaconda3\lib\site-packages (from requests->kagglehub) (2023.7.22)
Requirement already satisfied: colorama in c:\users\bethw\anaconda3\lib\site-packages (from tqdm->kagglehub) (0.4.6)

In [3]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("middlelight/goodreadsbookswithgenres")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\bethw\.cache\kagglehub\datasets\middlelight\goodreadsbookswithgenres\versions\1

In [4]:
import os
files = os.listdir(path)
print(files)

['Goodreads_books_with_genres.csv']

In [5]:
import pandas as pd

df = pd.read_csv(os.path.join(path, "Goodreads_books_with_genres.csv"))

df.head()

,Book Id,Title,Author,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher,genres
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,0439785960,9780439785969,eng,652,2095690,27591,9/16/2006,Scholastic Inc.,"Fantasy;Young Adult;Fiction;Fantasy,Magic;Chil..."
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,0439358078,9780439358071,eng,870,2153167,29221,9/1/2004,Scholastic Inc.,"Fantasy;Young Adult;Fiction;Fantasy,Magic;Chil..."
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,0439554896,9780439554893,eng,352,6333,244,11/1/2003,Scholastic,"Fantasy;Fiction;Young Adult;Fantasy,Magic;Chil..."
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,043965548X,9780439655484,eng,435,2339585,36325,5/1/2004,Scholastic Inc.,"Fantasy;Fiction;Young Adult;Fantasy,Magic;Chil..."
4,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,0439682584,9780439682589,eng,2690,41428,164,9/13/2004,Scholastic,"Fantasy;Young Adult;Fiction;Fantasy,Magic;Adve..."

In [6]:
df.columns

Index(['Book Id', 'Title', 'Author', 'average_rating', 'isbn', 'isbn13',
       'language_code', 'num_pages', 'ratings_count', 'text_reviews_count',
       'publication_date', 'publisher', 'genres'],
      dtype='object')

In [7]:
df = df.dropna(subset=["Title", "Author", "num_pages", "genres"])

In [8]:
def clean_genre(g):
    return g.split(",")[0].strip().lower()

df["genre_clean"] = df["genres"].apply(clean_genre)

In [9]:
def map_length(pages):
    if pages < 150:
        return "Short"
    elif pages < 300:
        return "Medium"
    else:
        return "Long"
    
df["length"] = df["num_pages"].apply(map_length)

In [10]:
df = df.drop_duplicates(subset=["isbn"], keep='first')

In [11]:
df.describe()

,Book Id,average_rating,isbn13,num_pages,ratings_count,text_reviews_count
count,11030.000000,11030.000000,1.103000e+04,11030.000000,1.103000e+04,11030.000000
mean,21305.474705,3.937976,9.762216e+12,337.682865,1.809403e+04,546.611061
std,13081.859562,0.325159,4.179528e+11,240.922013,1.129604e+05,2586.978923
min,1.000000,0.000000,8.987060e+09,0.000000,0.000000e+00,0.000000
25%,10310.250000,3.770000,9.780345e+12,195.000000,1.100000e+02,9.000000
50%,20256.000000,3.960000,9.780571e+12,301.000000,7.675000e+02,48.000000
75%,32081.500000,4.130000,9.780872e+12,416.000000,5.071500e+03,242.000000
max,45641.000000,5.000000,9.790008e+12,6576.000000,4.597666e+06,94265.000000

In [12]:
df.to_csv("cleaned_books.csv", index=False)

In [13]:
df["text"] = (df["Title"] + " " + df["Author"] + " " + df["genres"])